baseURL = 'https://dpbmdev.com/'
languageCode = 'en-us'
title = 'DPBM Blog'
theme = "shibui"

[services]
  [services.googleAnalytics]
    id = 'G-Q12P7E4HC9'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[params]
	[params.author]
	  name = "Dpbm"
	  email = "dpbm136@gmail.com"
[markup]
   [markup.goldmark]
      [markup.goldmark.renderer]
         unsafe = true

