baseURL = 'https://dpbmdev.com/'
languageCode = 'en-us'
title = 'DPBM Blog'
theme = "shibui"


[params]
	[params.author]
	  name = "Dpbm"
	  email = "dpbm136@gmail.com"
[markup]
   [markup.goldmark]
      [markup.goldmark.renderer]
         unsafe = true

